services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysqlvol:/var/lib/mysql
      - ./db/initialize.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysqlvol:
