name: Build and Release
on:
    push:
        branches:
            - main
jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup build environment
              run: sudo apt install -y build-essential libmysqlcppconn-dev
            - name: Build
              run: make all
            - name: Change name
              run: mv ./leetracker ./leetracker-linux-amd64
            
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: "latest"
                  prerelease: false
                  files: |
                      leetracker-linux-amd64
                  commit_message: "Release v${{ github.run_number }}"
                  release_title: "Release v${{ github.run_number }}"
                  release_body: |
                      Release v${{ github.run_number }}